MODEL:
  BACKBONE: "osnet_x0_25"
  PRETRAIN_PATH: "osnet_x0_25_msmt17.pt"
  DEVICE: "cpu"  # or "cuda"
  
TRACKER:
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100
